global:
  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: prometheus-stack-efs-sc
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
            selector: {}
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: prometheus-stack-efs-sc
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
            selector: {}
